### ISSUE TITLE
Vertical alignment of text field

### ISSUE THREAD

**Issue by cozyplanes** [cozyplanes/dB-UI#17]
The vertical alignment of text field is kinda awkward, and I can't find the issue.
https://i.imgur.com/9V8VmFz.png

**Comment by cozyplanes** [comment]
@LoganS1 @Kimmax

**Comment by Bobj2018** [comment]
I think I know what the issue is. I'll go and see what I can do.

Edit: has it been fixed?

**Comment by cozyplanes** [comment]
No, the vertical alignment of two text fields isn't correct. There seems to be an issue with the css while doing the responsive design, but I can't find it

**Comment by Kimmax** [comment]
Setting the `line-height` of the label to the height of the input will probably align them vertically
