### ISSUE TITLE
Is there a way to disable autocomplete?

### ISSUE THREAD

**Issue by cozyplanes** [cozyplanes/dB-UI#18]
Image:
https://i.imgur.com/KDb0m9b.png

**Comment by cozyplanes** [comment]
@LoganS1 @Kimmax

**Comment by cozyplanes** [comment]
And i believe `autocomplete="false"` solves this but it doesn't effect it.....

**Comment by falcon-head** [comment]
@cozyplanes Add `autocomplete="off"` instead of `autocomplete="false".`

**Comment by cozyplanes** [comment]
not needed anymore since the cookie feature has been implemented
