### ISSUE TITLE
Temp frontend V2

### ISSUE THREAD

**Issue by Kimmax** [cozyplanes/dB-UI#2]
So I did a quick frontend overhault for the temporary frontend.
Let me know what you think. Site is over at https://github.com/devBanner/devBanner_Frontend/tree/frontend_temp_v2
I'm not a frontend guy, so feel free to fix the CSS hacks 🗡 

https://imgur.com/a/HewNP

@cozyplanes do you like it?

**Comment by LoganS1** [comment]
It needs some work, but it looks good so far! I might be able to help later, although I'm pretty busy for a few days. :+1:

**Comment by Kimmax** [comment]
For example - it's not responsive at all 😂

**Comment by cozyplanes** [comment]
yup, maybe change the title font to `comfortaa` and make the text white color scheme

**Comment by LoganS1** [comment]
I have submitted a pull request for this,  #6

**Comment by cozyplanes** [comment]
New frontend, check out #6
