### ISSUE TITLE
Hovering over generate/download buttons after banner generation have a different color when hover

### ISSUE THREAD

**Issue by cozyplanes** [cozyplanes/dB-UI#37]
Generate btn:

![2018-05-13 22_18_30-devbanner - create your own devrant banner](https://user-images.githubusercontent.com/25971070/39967704-b4f54c36-56fb-11e8-89dd-1aa95b40a4ee.png)

Download btn:

![2018-05-13 22_18_41-devbanner - create your own devrant banner](https://user-images.githubusercontent.com/25971070/39967709-be54e688-56fb-11e8-9f31-da3c4ccdf87e.png)

**Comment by cozyplanes** [comment]
@Skayo

**Comment by Kimmax** [comment]
They do have the same tint, but the "Download" text isn't white on hover

**Comment by cozyplanes** [comment]
Yeah hover

**Comment by jonasgeiler** [comment]
Will fix asap
