### ISSUE TITLE
Add custom width feature

### ISSUE THREAD

**Issue by cozyplanes** [cozyplanes/dB-UI#38]
https://github.com/devBanner/devBanner/pull/43

It adds `&width=[128 ~ 2048 number here]` at the end of the request url

**Comment by jonasgeiler** [comment]
Wtf does [128 ~ 2048 number here] mean???

**Comment by jonasgeiler** [comment]
Will do as soon as possible

**Comment by cozyplanes** [comment]
@skayo it adds a value (width)
Such as
```
&width=128
&width=245
&width=648
&width=800
And all the way to 
&width=2048
```

**Comment by jonasgeiler** [comment]
Okay and should I do a slider or a drop down or just a number input?

**Comment by cozyplanes** [comment]
Slider  with a small textbox in the right would be nice

**Comment by cozyplanes** [comment]
@skayo can the current image preview handle smaller/bigger images??

**Comment by jonasgeiler** [comment]
Not really. The loading thing would probably be off center

**Comment by cozyplanes** [comment]
@skayo the backend code has heen updated, just need to deploy the front end

**Comment by jonasgeiler** [comment]
I currently don't have time to do it, will do asap

**Comment by cozyplanes** [comment]
Np
Take your time
Btw do you think black font is better than white font in yellow bg?

**Comment by jonasgeiler** [comment]
heh. good question...
Would need an example for that but it definitely depends on the font weight

**Comment by cozyplanes** [comment]
@Skayo https://devrant.com/rants/1456230

**Comment by jonasgeiler** [comment]
Oh okay, thanks.
Yeah white is definitely better

**Comment by cozyplanes** [comment]
@Skayo umm it seems you forgot PR to master (devBanner org)

**Comment by cozyplanes** [comment]
The margin in the right is a bit...... Strange

![](https://i.imgur.com/iiO7kF5.jpg)  

I am using S8 with curved edges tho

**Comment by jonasgeiler** [comment]
shh

**Comment by jonasgeiler** [comment]
will fix asap

**Comment by jonasgeiler** [comment]
Look #39
