### ISSUE TITLE
Problems with subtext right padding

### ISSUE THREAD

**Issue by agonxgashi** [cozyplanes/dB-UI#40]
In the image below:
> "This is a long text that apparently hit the right border of banner and it just looks ugly given that the image on the left has quite some padding from the left border!"

![image](https://user-images.githubusercontent.com/20556934/42454472-ed4cdcd2-838f-11e8-89ce-b918632dedaf.png)

**Comment by jonasgeiler** [comment]
That's actually a problem of the back-end. Please create the issue there.

**Comment by cozyplanes** [comment]
@agonxgashi It is going to be fixed today. Please wait and thank you for your interest!
