### ISSUE TITLE
Flare in edges

### ISSUE THREAD

**Issue by cozyplanes** [cozyplanes/dB-UI#7]
Can you fix this css issue?

![](https://i.imgur.com/656lL01.png)
@LoganS1

**Comment by LoganS1** [comment]
Hmmm, I don't get the issue..
![screenshot_20171223-092023](https://user-images.githubusercontent.com/21230472/34320592-4aa2457a-e7c3-11e7-8b45-1e5a8dd52638.png)
@Kimmax Can You test this?
@cozyplanes Are you on the most updated version?

Also can someone double check the CSS, I don't believe this should be happening as the filter (blur) is being applied to he image, and not the wrapper with is what crops the image to be on the screen, therefore the edges of the blur should be off-screen.

**Comment by Kimmax** [comment]
Can't reproduce. Don't know how that could happen, since the background image is oversized in width and height..
@CozyPlanes cache reload?

**Comment by cozyplanes** [comment]
https://devbanner.center

**Comment by cozyplanes** [comment]
Still same, but I think my webview version is low. I can't update it, so i think there is a bug with that. I will close for now, but of I come up with other ideas, will let you know.
